### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by joshjohanning** [broadtoad/Flight_Tracker#4]
This was just working 2 days ago. Did something change on the SW end?

```
flight_tracker -m /home/user/Flight_Tracker-master/multiple_flights.txt
2019-03-06 21:27:18,679 INFO Collected 3 flights to track from file
2019-03-06 21:27:18,681 INFO Collecting all available flights from MDW to OAK on 2019-07-04
Traceback (most recent call last):
  File "/usr/local/bin/flight_tracker", line 11, in <module>
    load_entry_point('flight-tracker==0.1', 'console_scripts', 'flight_tracker')()
  File "/usr/local/lib/python2.7/dist-packages/flight_tracker-0.1-py2.7.egg/flight_tracker/flight_tracker.py", line 77, in main
    check_all_flights(args, flight_searches, price_notifications)
  File "/usr/local/lib/python2.7/dist-packages/flight_tracker-0.1-py2.7.egg/flight_tracker/flight_tracker.py", line 41, in check_all_flights
    cheapest_flights = scrape_for_flights(flight_search)
  File "/usr/local/lib/python2.7/dist-packages/flight_tracker-0.1-py2.7.egg/flight_tracker/flight_tracker.py", line 18, in scrape_for_flights
    return find_cheapest_flights(flight_search)
  File "/usr/local/lib/python2.7/dist-packages/flight_tracker-0.1-py2.7.egg/flight_tracker/web_scraper.py", line 160, in find_cheapest_flights
    flights = retrieve_flight_data(flight_search, sw_api)
  File "/usr/local/lib/python2.7/dist-packages/flight_tracker-0.1-py2.7.egg/flight_tracker/web_scraper.py", line 123, in retrieve_flight_data
    raw_data = sw_api.retrieve_raw_flight_data(search_data)
  File "/usr/local/lib/python2.7/dist-packages/flight_tracker-0.1-py2.7.egg/flight_tracker/web_scraper.py", line 69, in retrieve_raw_flight_data
    return self.post(flight_api_url, data=json.dumps(search_data), headers=self._get_headers())
  File "/usr/local/lib/python2.7/dist-packages/flight_tracker-0.1-py2.7.egg/flight_tracker/web_scraper.py", line 47, in post
    result = self._check_status_code(response)
  File "/usr/local/lib/python2.7/dist-packages/flight_tracker-0.1-py2.7.egg/flight_tracker/web_scraper.py", line 41, in _check_status_code
    raise Exception(err.format(self.success_codes, status_code))
Exception: Invalid status code received. Expected [200]. Received 403.
```

**Comment by broadtoad** [comment]
I think so :(

I ran into the same issue. I'll take a closer look this weekend and see if there's anything I can do to fix!

**Comment by joshjohanning** [comment]
@broadtoad Did you get a chance to look into this? :)

**Comment by 209cameronism** [comment]
Same issue
